name: Build NotepadApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.12]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller qt-themes

    - name: Build executable
      run: |
        python compile.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NotepadApp-${{ matrix.os }}
        path: dist/*
